### ISSUE TITLE
Hexplot error when using visualization.py

### ISSUE THREAD

**Issue by gildepaz** [guaix-ucm/megaradrp#259] opened 2019-07-16 13:49 UTC
The use of hexplot in the current (distributed) version of visualization.py yields the following error:
_Traceback (most recent call last):
  File "/Users/agpaz/anaconda3/envs/megara/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/agpaz/anaconda3/envs/megara/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/agpaz/anaconda3/envs/megara/lib/python3.7/site-packages/megaradrp/visualization.py", line 433, in <module>
    main()
  File "/Users/agpaz/anaconda3/envs/megara/lib/python3.7/site-packages/megaradrp/visualization.py", line 373, in main
    col = hexplot(ax, x, y, zdisp, scale=scale, cmap=args.colormap, norm=norm)
  File "/Users/agpaz/anaconda3/envs/megara/lib/python3.7/site-packages/megaradrp/visualization.py", line 40, in hexplot
    if not axis._hold:
AttributeError: 'Axes' object has no attribute '_hold'_

**Comment by sergiopasra** [comment] 2019-07-24 15:29
Duplicate of #255

**Closed by sergiopasra** 2019-07-24 15:29 UTC
Labels: bug, duplicate
